// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
public class ConversorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\User\\Desktop\\Selenium Driver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void celsiusParaFahrenheit() {
    driver.get("http://localhost:8080/Conversor/ConversorTemperatura.html");
    driver.manage().window().setSize(new Dimension(1024, 608));
    driver.findElement(By.name("temperatura")).click();
    driver.findElement(By.name("temperatura")).sendKeys("100");
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("212.0 graus Fahrenheit"));
  }
  
  @Test
  public void FahrenheitParaCelsius() {
    driver.get("http://localhost:8080/Conversor/ConversorTemperatura.html");
    driver.manage().window().setSize(new Dimension(1024, 608));
    {
        WebElement dropdown = driver.findElement(By.id("transformacao"));
        dropdown.findElement(By.xpath("//option[. = 'Fahrenheit para Celsius']")).click();
      }
    driver.findElement(By.name("temperatura")).click();
    driver.findElement(By.name("temperatura")).sendKeys("212");
    driver.findElement(By.cssSelector("input:nth-child(6)")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("100.0 graus Celsius"));
  }
  
}
