// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class TradutorTest {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\User\\Desktop\\Selenium Driver\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  
  @Test
  public void primeiraPalavra() {
    driver.get("http://localhost:8080/tradutor/tradutor.html");
    driver.manage().window().setSize(new Dimension(1024, 608));
    driver.findElement(By.name("palavra")).click();
    driver.findElement(By.name("palavra")).sendKeys("cachorro");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("dog"));
  }
  
  @Test
  public void segundaPalavra() {
    driver.get("http://localhost:8080/tradutor/tradutor.html");
    driver.manage().window().setSize(new Dimension(1024, 608));
    driver.findElement(By.name("palavra")).click();
    driver.findElement(By.name("palavra")).sendKeys("pato");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("duck"));
  }
  
  @Test
  public void palavraInexistente() {
    driver.get("http://localhost:8080/tradutor/tradutor.html");
    driver.manage().window().setSize(new Dimension(1024, 608));
    driver.findElement(By.name("palavra")).click();
    driver.findElement(By.name("palavra")).sendKeys("cadeira");
    driver.findElement(By.cssSelector("input:nth-child(2)")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("cadeira"));
  }
  
}
